title: Grande e massivo título do blog
author: RC
email: rpcavaco@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Grande descrição for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
remote_theme: artemsheludko/flexible-jekyll

# social links
twitter_username: rpcavaco # DO NOT include the @ character, or else the build will fail!
github_username:  rpcavaco # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
